<?php
namespace LKDevelopment\UptimeMonitorAPI\Tests;

use LKDevelopment\UptimeMonitorAPI\UptimeMonitorAPIServiceProvider;
use Orchestra\Testbench\TestCase as Orchestra;

abstract class TestCase extends Orchestra
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->withFactories(__DIR__.'/../vendor/spatie/laravel-uptime-monitor/tests/factories');
    }

    /**
     * @param \Illuminate\Foundation\Application $app
     */
    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('database.default', 'sqlite');

        $app['config']->set('mail.driver', 'log');

        $app['config']->set('database.default', 'sqlite');
        $app['config']->set('database.connections.sqlite', [
            'driver' => 'sqlite',
            'prefix' => '',
            'database' => ':memory:',
        ]);

        $this->setUpDatabase();
    }

    protected function setUpDatabase()
    {
        include_once __DIR__ . '/../vendor/spatie/laravel-uptime-monitor/migrations/create_monitors_table.php.stub';

        (new \CreateMonitorsTable())->up();
    }

    /**
     * @param \Illuminate\Foundation\Application $app
     *
     * @return array
     */
    protected function getPackageProviders($app)
    {
        return [
            UptimeMonitorAPIServiceProvider::class,
        ];
    }
}